version: '3.8'

services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: bridgecore_api
    env_file:
      - ../.env
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/middleware_db
      - REDIS_URL=redis://redis:6379/0
      - ENVIRONMENT=production
      - DEBUG=False
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - ../app:/app/app
      - ../logs:/app/logs
    networks:
      - middleware_network
      - routy-traefik_web
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=routy-traefik_web"
      - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.bridgecore-web.rule=Host(`bridgecore.geniura.com`)"
      - "traefik.http.routers.bridgecore-web.entrypoints=web"
      - "traefik.http.routers.bridgecore-web.middlewares=https-redirect"
      - "traefik.http.routers.bridgecore-web.service=bridgecore"
      - "traefik.http.routers.bridgecore.rule=Host(`bridgecore.geniura.com`)"
      - "traefik.http.routers.bridgecore.entrypoints=websecure"
      - "traefik.http.routers.bridgecore.tls.certresolver=lehttp"
      - "traefik.http.routers.bridgecore.service=bridgecore"
      - "traefik.http.services.bridgecore.loadbalancer.server.port=8000"
    restart: unless-stopped

  db:
    image: postgres:15
    container_name: bridgecore_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=middleware_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - middleware_network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: bridgecore_redis
    volumes:
      - redis_data:/data
    networks:
      - middleware_network
    restart: unless-stopped


volumes:
  postgres_data:
  redis_data:

networks:
  middleware_network:
    driver: bridge
  routy-traefik_web:
    external: true
